### ISSUE TITLE
 [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by DhruvDange** [sigstore/sigstore-js#700]
**Description**
Keeping getting an error:
Failed to notarize the asset: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined.

Tried passing strings and json bodys too. Currently using this     
 const assetBuffer = Buffer.from(
      JSON.stringify(assetEnvelope),
       'utf-8'
     )

Using Sigstore-js latest version, same issue with @sigstore.sign

**Comment by bdehamer** [comment]
Based on the error, it would appear that the OIDC token that is being passed-in is either missing or not in the right form. The OIDC value should be a [JWT](https://datatracker.ietf.org/doc/html/rfc7519).

It's difficult to debug further without more context, but I am going to improve the error handling around this case so that you can at least get some more helpful information when this happens.
